---
- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mariadb
   - mariadb-server
   - mariadb-libs
   - mariadb-devel
   - MySQL-python
   - libselinux-python
   - libsemanage-python
   - curl
   - apache

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Start Mysql Service
  service: name=mariadb state=started enabled=yes
